# Generated by Django 4.1.7 on 2023-05-23 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('active_status', models.BooleanField(db_column='active_status', default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True, db_column='token', null=True)),
                ('provider', models.CharField(blank=True, db_column='provider', max_length=50, null=True)),
                ('token_creation_time', models.DateTimeField(auto_now_add=True, db_column='token_creation_time')),
                ('expire_time', models.IntegerField(blank=True, db_column='expire_time', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
