# Generated by Django 4.1.7 on 2025-05-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_config', '0004_reasoncode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationdimensioncode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reasoncode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returnreason',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='reason_code',
            field=models.CharField(blank=True, db_column='reason_code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='reason_description',
            field=models.CharField(db_column='reason_description', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='returnreason',
            name='reason_code',
            field=models.CharField(blank=True, db_column='reason_code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnreason',
            name='reason_description',
            field=models.CharField(db_column='reason_description', max_length=50, unique=True),
        ),
    ]
