# Generated by Django 4.1.7 on 2025-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_config', '0005_alter_locationdimensioncode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='gl_no',
            field=models.CharField(blank=True, db_column='gl_no', max_length=20, null=True),
        ),
    ]
