# Generated by Django 4.1.7 on 2025-06-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_config', '0006_paymentgateway_gl_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authusertoken',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='jobconfiguration',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='locationdimensioncode',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='reasoncode',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='returnreason',
            name='active_status',
        ),
    ]
