# Generated by Django 5.2.17 on 2026-08-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_config', '0007_remove_authusertoken_active_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reasoncode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reasoncode',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='returnreason',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='returnreason',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='LocationDimensionCode',
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
        migrations.DeleteModel(
            name='ReasonCode',
        ),
        migrations.DeleteModel(
            name='ReturnReason',
        ),
    ]
